print("\nJei Ho")
print("9/8/2019")
print("This code starts a conversation with the user")
print("Sources: None")
print("OMH")
user_name = input("\nHello, what's your name? ")
input("Cool name "+user_name+"! "+"What's your favorite sport? ")
user_food = input("Nice! My friend plays that too! Favorite food? ")
input("Interesting...my grandma is really good at making "+user_food+". Favorite place? ")
user_musician = input("Fascinating! That's one place I hope to go to in my bucket list. Favorite musician, if you had to name one? ")
input("No way! I was at "+user_musician+"'s concert the other day. Favorite book? ")
print("Wow! You and I have a lot in common!")